// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Backbone.SharedModel = (function(_super) {

    __extends(SharedModel, _super);

    function SharedModel(attributes, options) {
      SharedModel.__super__.constructor.call(this, attributes, options);
      this.doc = options && options.doc;
      if (!this.collection) {
        this.initializeSharing();
      }
    }

    SharedModel.prototype.initializeSharing = function() {
      var _this = this;
      if (this.collection) {
        this.doc = this.collection.doc;
      }
      if (this.sharedCollections) {
        _.each(this.sharedCollections, function(collectionKey) {
          var collection;
          collection = _this[collectionKey];
          if (collection) {
            return _this[collectionKey].initializeSharing({
              parent: _this,
              doc: _this.doc
            });
          }
        });
      }
      if (this.sharedAttributes) {
        return _.each(this.sharedAttributesKeys, function(attr) {
          return _this.on("change:" + attr, function(model, value) {
            return _this.updateSharedAttr(attr, _this._previousAttributes[attr], value);
          });
        });
      }
    };

    SharedModel.prototype.updatePath = function() {
      if (this.collection) {
        return this.collection.updatePath().concat([this.index]);
      } else {
        return [];
      }
    };

    SharedModel.prototype.attrSubdoc = function(attr) {
      return this.doc.at(this.updatePath().concat([attr]));
    };

    SharedModel.prototype.sharedAttributes = function() {
      return _.pick(this.attributes, this.sharedAttributesKeys);
    };

    SharedModel.prototype.destroy = function(options) {
      if (!(options && options.fromSharedOp)) {
        this.destroyed();
      }
      return SharedModel.__super__.destroy.call(this, options);
    };

    SharedModel.prototype.updateSharedAttr = function(attr, old_value, value) {
      return this.attrSubdoc(attr).set(value);
    };

    SharedModel.prototype.applySharedAction = function(actions) {
      var _this = this;
      return _.each(actions, function(action) {
        if (action.li) {
          _this.insertModel(action);
        }
        if (action.oi) {
          _this.setAttribute(action);
        }
        if (action.ld) {
          return _this.destroyModel(action);
        }
      });
    };

    SharedModel.prototype.isShareCollection = function(collectionName) {
      return _.contains(current.sharedCollections, next);
    };

    SharedModel.prototype.insertModel = function(action) {
      var _this = this;
      return _.reduce(_.initial(action.p), function(current, next) {
        if (_.isNumber(next)) {
          return current.models[next];
        } else {
          return current[next];
        }
      }, this).add(action.li, {
        fromSharedOp: true
      });
    };

    SharedModel.prototype.setAttribute = function(action) {
      var pathMaxDepth,
        _this = this;
      pathMaxDepth = action.p.length - 1;
      return _.reduce(action.p, function(current, next, index) {
        var isLastIndex, isSharedCollection, node;
        if (_.isNumber(next)) {
          return current.models[next];
        } else {
          node = current[next];
          isLastIndex = index === pathMaxDepth;
          isSharedCollection = _.contains(current.sharedCollections, next);
          if (isLastIndex && isSharedCollection) {
            return node.reset(action.oi, {
              silent: false,
              fromSharedOp: true
            });
          } else if (node) {
            return node;
          } else {
            return current.set(next, action.oi);
          }
        }
      }, this);
    };

    SharedModel.prototype.destroyed = function(options) {
      return this.doc.at(this.updatePath()).remove();
    };

    SharedModel.prototype.destroyModel = function(action) {
      var model,
        _this = this;
      model = _.reduce(action.p, function(current, next) {
        if (_.isNumber(next)) {
          return current.models[next];
        } else {
          return current[next];
        }
      }, this);
      return model.destroy({
        fromSharedOp: true
      });
    };

    return SharedModel;

  })(Backbone.Model);

  Backbone.SharedCollection = (function(_super) {

    __extends(SharedCollection, _super);

    SharedCollection.prototype.path = null;

    function SharedCollection(models, options) {
      var _this = this;
      SharedCollection.__super__.constructor.call(this, models, options);
      this.on("add destroy", function() {
        return _this.processIndexes();
      });
      this.on("reset", function() {
        return _this.setDoc();
      });
    }

    SharedCollection.prototype.initializeSharing = function(options) {
      var _this = this;
      this.on("add", this.triggerSharedAdd, this);
      this.parent = options.parent;
      this.setDoc(options.doc);
      this.processIndexes();
      return _.each(this.models, function(model) {
        return model.initializeSharing();
      });
    };

    SharedCollection.prototype.subdoc = function() {
      return this.doc.at(this.updatePath());
    };

    SharedCollection.prototype.setDoc = function(doc) {
      var updatePath;
      if (doc == null) {
        doc = null;
      }
      if (doc) {
        this.doc = doc;
      }
      try {
        this.subdoc().get();
        updatePath = this.updatePath().join('-');
        if (this.listening !== updatePath) {
          return this.listening = updatePath;
        }
      } catch (_error) {}
    };

    SharedCollection.prototype.updatePath = function() {
      return this.parent.updatePath().concat([this.path]);
    };

    SharedCollection.prototype.processIndexes = function() {
      var _this = this;
      return this.each(function(model, index) {
        model.index = index;
        return model.trigger("indexed");
      });
    };

    SharedCollection.prototype.modelAdded = function(model) {
      if (this.subdoc().get() === void 0) {
        this.subdoc().set([model.sharedAttributes()]);
        return this.setDoc();
      } else {
        return this.subdoc().push(model.sharedAttributes());
      }
    };

    SharedCollection.prototype.triggerSharedAdd = function(model, coll, options) {
      model.initializeSharing();
      if (!(options && options.fromSharedOp)) {
        return this.modelAdded(model);
      }
    };

    return SharedCollection;

  })(Backbone.Collection);

}).call(this);
