// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Backbone.SharedModel = (function(_super) {

    __extends(SharedModel, _super);

    function SharedModel(attributes, options) {
      var _this = this;
      SharedModel.__super__.constructor.call(this, attributes, options);
      _.each(this.sharedAttributesKeys, function(attr) {
        return _this.on("change:" + attr, function(model, value) {
          return _this.updateSharedAttr(attr, _this._previousAttributes[attr], value);
        });
      });
    }

    SharedModel.prototype.updatePath = function() {
      if (this.collection) {
        return this.collection.updatePath().concat([this.index]);
      } else {
        return [];
      }
    };

    SharedModel.prototype.sharedAttributes = function() {
      return _.pick(this.attributes, this.sharedAttributesKeys);
    };

    SharedModel.prototype.updateSharedAttr = function(attr, old_value, value) {
      console.log("Submit op : ", this.updatePath().concat([attr]), " - oi :", value);
      return window.doc.submitOp([
        {
          p: this.updatePath().concat([attr]),
          od: old_value,
          oi: value
        }
      ]);
    };

    SharedModel.prototype.applySharedAction = function(actions) {
      var _this = this;
      return _.each(actions, function(action) {
        if (action.oi) {
          return _this.setAttribute(action);
        }
      });
    };

    SharedModel.prototype.setAttribute = function(action) {
      var _this = this;
      return _.reduce(action.p, function(current, next) {
        var node;
        if (_.isNumber(next)) {
          return current.models[next];
        } else if (node = current[next]) {
          return node;
        } else {
          return current.set(next, action.oi);
        }
      }, this);
    };

    SharedModel.prototype.insertModel = function(action) {
      var _this = this;
      return _.reduce(action.p, function(current, next) {
        var model, node;
        switch (false) {
          case !_.isNumber(next):
            if ((model = current.models[next])) {
              return model;
            } else {
              return current.add(action.li);
            }
            break;
          case !(node = current[next]):
            return node;
        }
      }, this);
    };

    return SharedModel;

  })(Backbone.Model);

  Backbone.SharedCollection = (function(_super) {

    __extends(SharedCollection, _super);

    SharedCollection.prototype.path = null;

    function SharedCollection(models, options) {
      var _this = this;
      SharedCollection.__super__.constructor.call(this, models, options);
      this.processIndexes();
      this.on("add", function() {
        return _this.processIndexes();
      });
      this.subdoc = window.doc.at(this.updatePath());
      this.on("add.share", function(model) {
        return _this.modelAdded(model);
      });
      this.subdoc.on("insert", function(pos, data) {
        return _this.add(data, {
          fromSharedOp: true
        });
      });
    }

    SharedCollection.prototype.updatePath = function() {
      return this.parent.updatePath().concat([this.path]);
    };

    SharedCollection.prototype.processIndexes = function() {
      var _this = this;
      return this.each(function(model, index) {
        return model.index = index;
      });
    };

    SharedCollection.prototype.modelAdded = function(model) {
      return this.subdoc.push(model.sharedAttributes());
    };

    SharedCollection.prototype.add = function(models, options) {
      var triggerSharedAdd,
        _this = this;
      triggerSharedAdd = function(model, coll, opt) {
        if (!(options && options.fromSharedOp)) {
          return _this.trigger('add.share', model, coll, opt);
        }
      };
      this.on("add", triggerSharedAdd);
      SharedCollection.__super__.add.call(this, models, options);
      return this.off("add", triggerSharedAdd);
    };

    return SharedCollection;

  })(Backbone.Collection);

}).call(this);
